### ISSUE TITLE
papers or books

### ISSUE THREAD

**Issue by ccq195** [dleliuhin/PSO-Image-Enhancementer#3]
Are there some papers or books that i can reference about this project? Looking forward to your reply

**Comment by dleliuhin** [comment]
Hy, friend! Personally, I used the following literature:
--KumarGaurav, HarishBansal, ParticleSwarmOptimization (PSO) Technique for Image Enhancement // M.M.E.C, Mullana, Haryana, India, IJECT Vol. 4, Issue Spl -3, April -June 2013, 3 pages.2.

--Nirmal Singh, Maninder Kaur, K.V.P Singh, Parameter Optimization InImage Enhancement Using PSO // American Journal of Engineering Research (AJER) Volume-02, Issue-05, pp-84-90.

--Kai Hu, Aiguo Song, Min Xia, Zhiyong Fan, Xiaoying Chen, Ruidong Zhang, Zhichen Zheng, An Image Filter Based on Shearlet Transformation andParticle Swarm Optimization Algorithm// Research Article.

--A. J. Onumanyi, F. Idris, M. B. Abdullahi, H. Bello-Salau,  S. O. Aliyu, M. Okwori, Automatic Gray Image Contrast Enhancement using Particle  Swarm and Cuckoo Search Optimization Algorithms // International Conference on Informatio n and Communication Technology and Its Applications(ICTA 2016).

--I. Aleksandar Lazinica, Particle  Swarm Optimization, Published by In-TechIn-Tech Kirchengasse 43/3, Rijeka, Croatia.

--С.И. Родзин, С.А. Эль-Хатиб, Совершенствование алгоритмов сегментации магнитно-резонансных изображений на основе роевого интеллекта // Информатика, вычислительная техника и управление, Вестник Чувашского университета. 2016. No 37.Ю.И. Монич, В.В. Старовойтов, Оценки качества для анализацифровыхизображений
